### ISSUE TITLE
Not DELETE the product (item_del) 

### ISSUE THREAD

**Issue by volodymyr-dehtiarenko** [hjlarry/flask-shop#101]
Hi, I can not understand why the product is not deleted (from product_product), I checked on databases  MySql, Postgresql.... everything is removed except for the product. And the second question, if you add a product from the dashboard, then it is not added to the cart, if do by the seed command ....works. 
Thanks for your help!

**Comment by hjlarry** [comment]
the product delete code is [here](https://github.com/hjlarry/flask-shop/blob/master/flaskshop/dashboard_api/views.py#L27)
so it is just try delete from the db, if failed, you can check the response to see error details

for the second question, I don't understand `it is not added to the cart`, you mean  you can see the new product from the frontpage, but it can not add to the cart?

**Comment by volodymyr-dehtiarenko** [comment]
> the product delete code is [here](https://github.com/hjlarry/flask-shop/blob/master/flaskshop/dashboard_api/views.py#L27)
> so it is just try delete from the db, if failed, you can check the response to see error details

Thank you very much for the answer. I know the code and do not understand why it is not deleted only  "product_del = wrap_partial(item_del, Product)" I have an error ....

 "ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f362b7f31c0>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f362b7f31c0>: Failed to establish a new connection: [Errno 111] Connection refused)"

**Comment by volodymyr-dehtiarenko** [comment]
> for the second question, I don't understand `it is not added to the cart`, you mean you can see the new product from the frontpage, but it can not add to the cart?

Yes, exactly!

**Comment by hjlarry** [comment]
For the delete problem,   you can delete [this line](https://github.com/hjlarry/flask-shop/blob/master/flaskshop/product/models.py#L207)

that is a bug.  when you delete a product, will trigger this function, and will delete the product in the  Elasticsearch database. but the Elasticsearch was disabled by default, so that cause a ConnectionError to Elasticsearch

**Comment by hjlarry** [comment]
I can not reproduce the cart problem.  when you add to cart,  there is no any other hint? how about the db cart table, no new record?

**Comment by volodymyr-dehtiarenko** [comment]
> For the delete problem, you can delete [this line](https://github.com/hjlarry/flask-shop/blob/master/flaskshop/product/models.py#L207)
> 
> that is a bug. when you delete a product, will trigger this function, and will delete the product in the Elasticsearch database. but the Elasticsearch was disabled by default, so that cause a ConnectionError to Elasticsearch

Thank you very much it works!
