### ISSUE TITLE
Bug: Creating products with has_variant=False still requires a variant.

### ISSUE THREAD

**Issue by Google-bardAi** [hjlarry/flask-shop#108]
When creating a product type with the "Has variant" parameter set to False through the admin dashboard at "http://127.0.0.1:5000/dashboard/product_types," it is expected behavior that creating a product of this type would not require a variant. However, in the current implementation, even with "variant" set to False, the system mandates the creation of a variant for the product.

As a consequence, attempting to add such a product to the cart results in an issue. The form validation in "flask-shop/flaskshop/product/views.py" at line 28 expects a variant, causing the inability to submit and validate the form.

**Comment by hjlarry** [comment]
Acturally,  I forgot why I designed this `has_variants` attr. The variant is required for so many position, and the Product Model has a `generate_variants` [method](https://github.com/hjlarry/flask-shop/blob/master/flaskshop/product/models.py#L133) . Maybe it should be called when a product is created.

**Comment by Google-bardAi** [comment]
No planned
