### ISSUE TITLE
problem in realationship beatween tabels and dashboard page

### ISSUE THREAD

**Issue by MammadTavakoli** [hjlarry/flask-shop#15]
this work is huge. but there is not any relationship between tables , why?
and why dashboard page has not useful?
if i want change this to market place do you have any suggestion?

do you thinks this can work like woocammerce or saleor? in performance and ability?

**Comment by hjlarry** [comment]
Because foreign key in mysql is not good for performance.
The dashboard index page is in develop, I havn`t finish it.
This programe is for my practise, the ability and performance is less than saleor.

**Comment by MammadTavakoli** [comment]
thanks. how can change it to marketplace?

**Comment by hjlarry** [comment]
sorry，I can`t understand what marketplace means？
