### ISSUE TITLE
Error in step Second, Init db and run

### ISSUE THREAD

**Issue by UnknownFX02** [hjlarry/flask-shop#30]
Hi, i am try learn flask and i found this project but i have some error
after i modify .flaskenv and flaskshop/setting.py. i run `flask createdb` it throw error `Error: No such command 'createdb'`.
i was try `flask run` but it also throw` flask.cli.NoAppException: Could not import "autoapp".`
tks

**Comment by hjlarry** [comment]
seems it can not find the flask_app, try to set the env varible `FLASK_APP ` to the `autoapp.py` position

**Comment by UnknownFX02** [comment]
> seems it can not find the flask_app, try to set the env varible `FLASK_APP ` to the `autoapp.py` position

tks for reply. my problem is flask run can run but when go `localhost:5000` it throw `flask.cli.NoAppException: Could not import "autoapp"`, not at time run `flask run` like wrong position `autoapp.py`

**Comment by hjlarry** [comment]
like this problem? https://stackoverflow.com/questions/50574293/flask-cli-noappexception-could-not-import-flaskr-flaskr

**Comment by UnknownFX02** [comment]
It's quite similar to my case but i run `flask run` in flask-shop dir,
 
here my flask-shop dir:
 ~/Downloads/STU/flask-shop: **ls**
`autoapp.py`  `docker-compose.yml`  `Dockerfile`  `flaskshop`  `LICENSE`  `mpvue`  `package.json`  `package-lock.json`  `plugin_example`  `README.md`  `requirements.txt`  `ScreenShot`  `tests`  `webpack-bundle.json`  `webpack.config.js`

here full traceback `flask run`
 ~/Downloads/STU/flask-shop: **flask run**
 * Serving Flask app "autoapp.py" (lazy loading)
 * Environment: develop
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 958-709-826
127.0.0.1 - - [10/Jun/2020 09:28:16] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/phuongdai/Downloads/STU/flask-shop/.venv/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
ModuleNotFoundError: No module named 'autoapp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/phuongdai/Downloads/STU/flask-shop/.venv/lib/python3.8/site-packages/flask/cli.py", line 338, in __call__
    self._flush_bg_loading_exception()
  File "/home/phuongdai/Downloads/STU/flask-shop/.venv/lib/python3.8/site-packages/flask/cli.py", line 326, in _flush_bg_loading_exception
    reraise(*exc_info)
  File "/home/phuongdai/Downloads/STU/flask-shop/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/phuongdai/Downloads/STU/flask-shop/.venv/lib/python3.8/site-packages/flask/cli.py", line 314, in _load_app
    self._load_unlocked()
  File "/home/phuongdai/Downloads/STU/flask-shop/.venv/lib/python3.8/site-packages/flask/cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "/home/phuongdai/Downloads/STU/flask-shop/.venv/lib/python3.8/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/home/phuongdai/Downloads/STU/flask-shop/.venv/lib/python3.8/site-packages/flask/cli.py", line 250, in locate_app
    raise NoAppException('Could not import "{name}".'.format(name=module_name))
flask.cli.NoAppException: Could not import "autoapp".
127.0.0.1 - - [10/Jun/2020 09:28:16] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [10/Jun/2020 09:28:16] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [10/Jun/2020 09:28:16] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [10/Jun/2020 09:28:16] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [10/Jun/2020 09:28:16] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [10/Jun/2020 09:28:16] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
And i was try in a virtualbox ubuntu 18.04 it also show same problem. tks

**Comment by hjlarry** [comment]
can you try `which flask`, this flask may your system`s flask, not your virual env`s flask

**Comment by UnknownFX02** [comment]
`which flask`                                                                                                                                                                                                                                                                                            
/home/phuongdai/Downloads/STU/flask-shop/**.venv**/bin/flask

**Comment by hjlarry** [comment]
emmm.... this need to debug..   
try to modify `/home/phuongdai/Downloads/STU/flask-shop/.venv/lib/python3.8/site-packages/flask/cli.py`   
add `print(sys.path)` to see is it load your current work dir?  if not, you can try to add it to see is it work.

**Comment by UnknownFX02** [comment]
Ok tks you for spend time to me, can you answer me this is a bug or my wrong, i will try to fix this. And i just try docker but it aslo get error when build web @@

**Comment by hjlarry** [comment]
I haven\`t meet this problem ever before,  so I don\`t know is this a bug.
maybe after several month some dependence project version changed，I will try to run this project in a new env later when I am free.
