### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by intxff** [hjlarry/flask-shop#47]
1. 类型不匹配，self.xxx_date 是 datetime.date，datetime.now() 应该要 datetime.date(datime.now()) 转成 date 

https://github.com/hjlarry/flask-shop/blob/104bcf447ca12b0d2264fc5401cb40c5defeab93/flaskshop/discount/models.py#L62

2. type 和 type_ 名称错了

https://github.com/hjlarry/flask-shop/blob/104bcf447ca12b0d2264fc5401cb40c5defeab93/flaskshop/discount/models.py#L74

3. discount 表应该还要添加一个已经使用 voucher 的用户的表，不然一个码子可以被同一个人多次使用

**Comment by hjlarry** [comment]
1和2感谢提出 👍🏻 
3其实本身就是这么设计的，您如果用过亚马逊的话，它们也是这么设计的

**Comment by hjlarry** [comment]
fixed
