### ISSUE TITLE
Demo doesn't run with docker-compose

### ISSUE THREAD

**Issue by rweickelt** [hjlarry/flask-shop#98]
I tried 

```
docker-compose build
docker-compose up
```

and got a connection error when typing http://127.0.0.1:5000 in my browser. After changing the start line in `Dockerfile` to 

```
CMD ["flask", "run", "--host=0.0.0.0"]
```

my browser can connect, but I get "Internal Error 500" in my browser. Could you please provide instructions how to use the Docker container?

**Comment by hjlarry** [comment]
maybe you can try to modify the dockerfile:
`CMD ["flask", "run", "--debug", "--host=0.0.0.0"]`
to open the debug mode, and will see the error detail
I haven't install the docker. I will fix this some days later

**Comment by rweickelt** [comment]
You mean the option `--debugger`? OK, I did that and now my browser shows a long exception trace. Most interesting seems this failing SQL query:
```
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'flaskshop.public_menuitem' doesn't exist")
[SQL: SELECT public_menuitem.url AS public_menuitem_url, public_menuitem.id AS public_menuitem_id, public_menuitem.created_at AS public_menuitem_created_at, public_menuitem.updated_at AS public_menuitem_updated_at, public_menuitem.title AS public_menuitem_title, public_menuitem.`order` AS public_menuitem_order, public_menuitem.category_id AS public_menuitem_category_id, public_menuitem.collection_id AS public_menuitem_collection_id, public_menuitem.position AS public_menuitem_position, public_menuitem.page_id AS public_menuitem_page_id, public_menuitem.parent_id AS public_menuitem_parent_id 
FROM public_menuitem 
WHERE public_menuitem.position = %(position_1)s AND public_menuitem.parent_id = %(parent_id_1)s ORDER BY public_menuitem.`order`]
[parameters: {'position_1': 1, 'parent_id_1': 0}]
(Background on this error at: https://sqlalche.me/e/14/f405)

```

**Comment by dedalgr** [comment]
Create DB table

На пн, 6.02.2023 г., 11:35 ч. Richard Weickelt ***@***.***>
написа:

**Comment by rweickelt** [comment]
Thanks for the hint. I noticed that I overlooked the "Installation" instructions. After creating the tables and seeding the project it works now.

**Comment by rweickelt** [comment]
The issue with `--host` remains and I am not familiar enough with this project to fix it. So I leave it open.

**Comment by hjlarry** [comment]
> The issue with `--host` remains and I am not familiar enough with this project to fix it. So I leave it open.

you are right, when docker runs, we need to specify the host to access it outside the docker. Thanks!
